services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  filebeat:
    image: public.ecr.aws/elastic/filebeat:sha256-ce560daed8a62f98a7005fdf96a88eea12dacdcaa4c0154af28a6fe752843c19
    container_name: filebeat
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
    command: filebeat -e --strict.perms=false


volumes:
  grafana-storage: {}